default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: quora_app_development
  username: chirs
  password: chirs
  host: localhost
  port: 5432
